name: Continuous Integration

on: 
  push:
   branches:
    - master
  pull_request:

jobs:
  test:
    name: Lint and test
    uses: pkgjs/action/.github/workflows/node-test.yaml@v0
    with:
      strategy-fail-fast: true
      test-command: |
        npm run lint
        npm run test

  automerge:
    name: Merge dependabot's PRs
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
